name: Npm Publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  publish:
    name: Build And Publish
    runs-on: ubuntu-latest
    steps:
      - name: Get Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build2Publish
        run: |
          npm install
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
